Sprint 1/step 2
yarsmirnov/praktikum_react-burger pull request #2
Opened 2021-07-27 18:47 UTC by yarsmirnov

Это первое ревью, поэтому готов к любым пожеланиям и рекомендациям.

2021-07-28 12:58 UTC, AygulMalikova requested changes
Отличная работа! 

У вас хорошо структурированный и чистый код, разделенный на компоненты, весь необходимый функционал реализован и работает верно!

Но есть небольшие замечания. В первую очередь прошу вас обратить внимание на реализацию модального окна. Пожалуйста, вынесите тип ингредиента в отдельный файл. И также, были оставлены другие комментарии и рекомендации по улучшению вашего кода.

Я напоминаю, что работа будет принята, как только все критические ошибки будут исправлены. Желаю вам удачи!

2021-07-28 12:58 UTC, AygulMalikova commented on src/components/burger-constructor/burger-constructor.tsx
> +    console.log('Oh, no. I was clicked!');
Можно лучше:

Перед отправкой работы, пожалуйста, убедитесь в том, что все строки кода содержащие debugger и console.log удалены.

2021-07-28 12:58 UTC, AygulMalikova commented on src/components/burger-ingredient-card/burger-ingredient-card.tsx
>    name: PropTypes.string.isRequired,
**Надо исправить:**
Как вы можете заметить, тип ингредиента дублируется в нескольких компонентах. Представьте, что в один момент необходимо будет добавить/удалить/изменить одно поле, и тогда это придется делать в нескольких местах. Это нарушает принцип DRY (про него можно почитать в этой статье https://habr.com/ru/post/144611/). Вам следует вынести в отдельный тип, разместить его внутри utils и импортировать внутри компонентов, где он используется.

2021-07-28 12:58 UTC, AygulMalikova commented on src/components/modal-overlay/modal-overlay.tsx
> +  return modalRoot ? createPortal((
Надо исправить:

ModalOverlay - фоновая подложка под модальным окном. Создание портала следует вынести в компонент Modal. И внутри Modal использовать ModalOverlay, а не наоборот.  Вы можете обратиться к этому уроку в тренажере, чтобы освежить знания по этой теме: https://practicum.yandex.ru/learn/react/courses/b512c4ac-8797-4b96-935a-6b2865f27c9a/sprints/6021/topics/3daef531-37a0-4521-ac9c-dac879418335/lessons/f60fe57f-6c77-446c-966d-1fefe0413a9f/

2021-07-28 12:58 UTC, AygulMalikova commented on src/components/burger-constructor/burger-constructor.tsx
> +          createPortal((
Надо исправить:

ModalOverlay - фоновая подложка под модальным окном. Создание портала следует вынести в компонент Modal. И внутри Modal использовать ModalOverlay, а не наоборот. Вы можете обратиться к этому уроку в тренажере, чтобы освежить знания по этой теме: https://practicum.yandex.ru/learn/react/courses/b512c4ac-8797-4b96-935a-6b2865f27c9a/sprints/6021/topics/3daef531-37a0-4521-ac9c-dac879418335/lessons/f60fe57f-6c77-446c-966d-1fefe0413a9f/

Более того, вы можете использовать модальные окна в компоненте App (как показано в уроке)

2021-07-28 12:58 UTC, AygulMalikova commented on src/components/burger-ingredients/burger-ingredients.tsx
>          )}
Отлично, что вы реализовали навигацию по табам!

2021-07-29 07:58 UTC, yarsmirnov commented on src/components/burger-constructor/burger-constructor.tsx
> +    console.log('Oh, no. I was clicked!');
Привык, что разные линтеры по умолчанию жалуются на `console.log`.
Хорошо хоть перестал выводить в консоль ругательства :)

2021-07-29 08:01 UTC, yarsmirnov commented on src/components/burger-ingredient-card/burger-ingredient-card.tsx
>    name: PropTypes.string.isRequired,
Вынес в **utils** шаблон propTypes для ингредиента.
Также сделал адаптер, чтобы везде использовались одинаковые пропсы, а не `_id` и `id` или `image_large` и `imgLarge`.

2021-07-29 08:08 UTC, yarsmirnov commented on src/components/burger-ingredients/burger-ingredients.tsx
>          )}
Навигация не в лучшем виде :(
Иногда прокручивает страницу целиком, чтобы заголовок секции с ингредиентами оказался наверху страницы.

https://www.loom.com/share/91dc9748bc3c42ebb8d6126b60238ba5

2021-07-29 09:25 UTC, yarsmirnov commented on src/components/burger-constructor/burger-constructor.tsx
> +          createPortal((
Переделал так, чтобы `Modal` вызывал `ModalOverlay`.
Тема применения модальных окон в уроке слабо раскрыта :( Как мне кажется, модальные окна/оповещения достойны отдельного урока с теорией и практикой.

Если скажете, то переделаю логику так, чтобы модальные окна вызывались из App. Но сейчас я не вижу преимуществ в вызове модальных окон на уровне всего приложения, ведь придётся прокидывать функции через все компоненты-посредники и усложнять логику замыканием, вроде
```javascript
const showModal = (setIsModalActive) => (setShowContent) => {
  setShowContent(ingredientData или orderData);
  setIsModalActive(true);
}
```
_P.S.: Код очень условный. Накидал его не открывая проект._

2021-07-29 12:36 UTC, AygulMalikova requested changes
Очень хорошо! Вы исправили немало ошибок, и вы движетесь в правильном направлении!
Осталось исправить одну ошибку и ваша работа будет принята. Удачи!

2021-07-29 12:36 UTC, AygulMalikova commented on src/components/burger-constructor/burger-constructor.tsx
> +          createPortal((
Здесь вам следует удалить создание портала, т.к. теперь он создается внутри компонента Modal. Вам следует подключать модальное окно как внутри BurgerIngredientCard.

Модальные окна можете не переносить в App, это лишь рекомендация

2021-07-29 12:51 UTC, yarsmirnov commented on src/components/burger-constructor/burger-constructor.tsx
> +          createPortal((
Исправил.
Непонятно, зачем я `createPortal` здесь применял.

2021-07-29 12:52 UTC, yarsmirnov commented
Благодарю за ревью!
Успехов!

2021-07-29 14:37 UTC, AygulMalikova commented
Ваша работа принята, я вас поздравляю! Все ошибки исправлены и все условия задания выполнены. У вас отличный код, поделенный на компоненты. Так держать! Еще раз поздравляю и желаю вам дальнейших успехов!

2021-08-02 13:23 UTC, merged